
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry resbox;

	private global::Gtk.Entry numbox;

	private global::Gtk.Table table1;

	private global::Gtk.Button btn_1;

	private global::Gtk.Button btn_2;

	private global::Gtk.Button btn_3;

	private global::Gtk.Button btn_4;

	private global::Gtk.Button btn_5;

	private global::Gtk.Button btn_6;

	private global::Gtk.Button btn_7;

	private global::Gtk.Button btn_8;

	private global::Gtk.Button btn_9;

	private global::Gtk.Button btn_zero;

	private global::Gtk.Button clean;

	private global::Gtk.Button comma;

	private global::Gtk.Button div;

	private global::Gtk.Button equal;

	private global::Gtk.Button exp;

	private global::Gtk.Button minus;

	private global::Gtk.Button mult;

	private global::Gtk.Button percentage;

	private global::Gtk.Button root;

	private global::Gtk.Button sum;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.CanFocus = true;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = -11;
		// Container child vbox2.Gtk.Box+BoxChild
		this.resbox = new global::Gtk.Entry();
		this.resbox.HeightRequest = 80;
		this.resbox.Sensitive = false;
		this.resbox.CanFocus = true;
		this.resbox.Name = "resbox";
		this.resbox.IsEditable = false;
		this.resbox.HasFrame = false;
		this.resbox.InvisibleChar = '•';
		this.vbox2.Add(this.resbox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.resbox]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.numbox = new global::Gtk.Entry();
		this.numbox.HeightRequest = 73;
		this.numbox.CanFocus = true;
		this.numbox.Name = "numbox";
		this.numbox.IsEditable = false;
		this.numbox.MaxLength = 9;
		this.numbox.InvisibleChar = '•';
		this.vbox2.Add(this.numbox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.numbox]));
		w2.Position = 1;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(5)), false);
		this.table1.HeightRequest = 229;
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(1));
		this.table1.ColumnSpacing = ((uint)(1));
		// Container child table1.Gtk.Table+TableChild
		this.btn_1 = new global::Gtk.Button();
		this.btn_1.CanFocus = true;
		this.btn_1.Name = "btn_1";
		this.btn_1.UseUnderline = true;
		this.btn_1.FocusOnClick = false;
		this.btn_1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table1.Add(this.btn_1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_1]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_2 = new global::Gtk.Button();
		this.btn_2.CanFocus = true;
		this.btn_2.Name = "btn_2";
		this.btn_2.UseUnderline = true;
		this.btn_2.FocusOnClick = false;
		this.btn_2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table1.Add(this.btn_2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_2]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_3 = new global::Gtk.Button();
		this.btn_3.CanFocus = true;
		this.btn_3.Name = "btn_3";
		this.btn_3.UseUnderline = true;
		this.btn_3.FocusOnClick = false;
		this.btn_3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table1.Add(this.btn_3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_3]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_4 = new global::Gtk.Button();
		this.btn_4.CanFocus = true;
		this.btn_4.Name = "btn_4";
		this.btn_4.UseUnderline = true;
		this.btn_4.FocusOnClick = false;
		this.btn_4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table1.Add(this.btn_4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_4]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_5 = new global::Gtk.Button();
		this.btn_5.CanFocus = true;
		this.btn_5.Name = "btn_5";
		this.btn_5.UseUnderline = true;
		this.btn_5.FocusOnClick = false;
		this.btn_5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table1.Add(this.btn_5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_6 = new global::Gtk.Button();
		this.btn_6.CanFocus = true;
		this.btn_6.Name = "btn_6";
		this.btn_6.UseUnderline = true;
		this.btn_6.FocusOnClick = false;
		this.btn_6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table1.Add(this.btn_6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_6]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_7 = new global::Gtk.Button();
		this.btn_7.CanDefault = true;
		this.btn_7.CanFocus = true;
		this.btn_7.Name = "btn_7";
		this.btn_7.UseUnderline = true;
		this.btn_7.FocusOnClick = false;
		this.btn_7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table1.Add(this.btn_7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_7]));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btn_8 = new global::Gtk.Button();
		this.btn_8.CanFocus = true;
		this.btn_8.Name = "btn_8";
		this.btn_8.UseUnderline = true;
		this.btn_8.FocusOnClick = false;
		this.btn_8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table1.Add(this.btn_8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_8]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.btn_9 = new global::Gtk.Button();
		this.btn_9.CanFocus = true;
		this.btn_9.Name = "btn_9";
		this.btn_9.UseUnderline = true;
		this.btn_9.FocusOnClick = false;
		this.btn_9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table1.Add(this.btn_9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_9]));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.btn_zero = new global::Gtk.Button();
		this.btn_zero.CanFocus = true;
		this.btn_zero.Name = "btn_zero";
		this.btn_zero.UseUnderline = true;
		this.btn_zero.FocusOnClick = false;
		this.btn_zero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table1.Add(this.btn_zero);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.btn_zero]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.clean = new global::Gtk.Button();
		this.clean.CanFocus = true;
		this.clean.Name = "clean";
		this.clean.UseUnderline = true;
		this.clean.FocusOnClick = false;
		this.clean.Label = global::Mono.Unix.Catalog.GetString("C");
		this.table1.Add(this.clean);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.clean]));
		w13.LeftAttach = ((uint)(4));
		w13.RightAttach = ((uint)(5));
		// Container child table1.Gtk.Table+TableChild
		this.comma = new global::Gtk.Button();
		this.comma.CanFocus = true;
		this.comma.Name = "comma";
		this.comma.UseUnderline = true;
		this.comma.FocusOnClick = false;
		this.comma.Label = global::Mono.Unix.Catalog.GetString(",");
		this.table1.Add(this.comma);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.comma]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.div = new global::Gtk.Button();
		this.div.CanFocus = true;
		this.div.Name = "div";
		this.div.UseUnderline = true;
		this.div.FocusOnClick = false;
		this.div.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table1.Add(this.div);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.div]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.equal = new global::Gtk.Button();
		this.equal.CanFocus = true;
		this.equal.Name = "equal";
		this.equal.UseUnderline = true;
		this.equal.FocusOnClick = false;
		this.equal.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table1.Add(this.equal);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.equal]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.LeftAttach = ((uint)(4));
		w16.RightAttach = ((uint)(5));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.exp = new global::Gtk.Button();
		this.exp.CanFocus = true;
		this.exp.Name = "exp";
		this.exp.UseUnderline = true;
		this.exp.FocusOnClick = false;
		this.exp.Label = global::Mono.Unix.Catalog.GetString("x²");
		this.table1.Add(this.exp);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.exp]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(4));
		w17.RightAttach = ((uint)(5));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.minus = new global::Gtk.Button();
		this.minus.CanFocus = true;
		this.minus.Name = "minus";
		this.minus.UseUnderline = true;
		this.minus.FocusOnClick = false;
		this.minus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table1.Add(this.minus);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.minus]));
		w18.TopAttach = ((uint)(2));
		w18.BottomAttach = ((uint)(3));
		w18.LeftAttach = ((uint)(3));
		w18.RightAttach = ((uint)(4));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.mult = new global::Gtk.Button();
		this.mult.CanFocus = true;
		this.mult.Name = "mult";
		this.mult.UseUnderline = true;
		this.mult.FocusOnClick = false;
		this.mult.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table1.Add(this.mult);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.mult]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(3));
		w19.RightAttach = ((uint)(4));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.percentage = new global::Gtk.Button();
		this.percentage.CanFocus = true;
		this.percentage.Name = "percentage";
		this.percentage.UseUnderline = true;
		this.percentage.FocusOnClick = false;
		this.percentage.Label = global::Mono.Unix.Catalog.GetString("%");
		this.table1.Add(this.percentage);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.percentage]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.root = new global::Gtk.Button();
		this.root.CanFocus = true;
		this.root.Name = "root";
		this.root.UseUnderline = true;
		this.root.FocusOnClick = false;
		this.root.Label = global::Mono.Unix.Catalog.GetString("raiz");
		this.table1.Add(this.root);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.root]));
		w21.TopAttach = ((uint)(2));
		w21.BottomAttach = ((uint)(3));
		w21.LeftAttach = ((uint)(4));
		w21.RightAttach = ((uint)(5));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.sum = new global::Gtk.Button();
		this.sum.CanFocus = true;
		this.sum.Name = "sum";
		this.sum.UseUnderline = true;
		this.sum.FocusOnClick = false;
		this.sum.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table1.Add(this.sum);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.sum]));
		w22.TopAttach = ((uint)(3));
		w22.BottomAttach = ((uint)(4));
		w22.LeftAttach = ((uint)(3));
		w22.RightAttach = ((uint)(4));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add(this.table1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 289;
		this.DefaultHeight = 384;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.numbox.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnNumboxKeyPressEvent);
		this.sum.Clicked += new global::System.EventHandler(this.OnSumClicked);
		this.root.Clicked += new global::System.EventHandler(this.OnRootClicked);
		this.percentage.Clicked += new global::System.EventHandler(this.OnPercentageClicked);
		this.mult.Clicked += new global::System.EventHandler(this.OnMultClicked);
		this.minus.Clicked += new global::System.EventHandler(this.OnMinusClicked);
		this.exp.Clicked += new global::System.EventHandler(this.OnExpClicked);
		this.equal.Clicked += new global::System.EventHandler(this.OnEqualClicked);
		this.div.Clicked += new global::System.EventHandler(this.OnDivClicked);
		this.comma.Clicked += new global::System.EventHandler(this.OnCommaClicked);
		this.clean.Clicked += new global::System.EventHandler(this.OnCleanClicked);
		this.btn_zero.Clicked += new global::System.EventHandler(this.OnBtnZeroClicked);
		this.btn_9.Clicked += new global::System.EventHandler(this.OnBtn9Clicked);
		this.btn_8.Clicked += new global::System.EventHandler(this.OnBtn8Clicked);
		this.btn_7.Clicked += new global::System.EventHandler(this.OnBtn7Clicked);
		this.btn_6.Clicked += new global::System.EventHandler(this.OnBtn6Clicked);
		this.btn_5.Clicked += new global::System.EventHandler(this.OnBtn5Clicked);
		this.btn_4.Clicked += new global::System.EventHandler(this.OnBtn4Clicked);
		this.btn_3.Clicked += new global::System.EventHandler(this.OnBtn3Clicked);
		this.btn_2.Clicked += new global::System.EventHandler(this.OnBtn2Clicked);
		this.btn_1.Clicked += new global::System.EventHandler(this.OnBtn1Clicked);
	}
}
