
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry resbox;

	private global::Gtk.Entry numbox;

	private global::Gtk.Table table1;

	private global::Gtk.Button button10;

	private global::Gtk.Button button11;

	private global::Gtk.Button button12;

	private global::Gtk.Button button13;

	private global::Gtk.Button button14;

	private global::Gtk.Button button15;

	private global::Gtk.Button button16;

	private global::Gtk.Button button17;

	private global::Gtk.Button button18;

	private global::Gtk.Button button19;

	private global::Gtk.Button button20;

	private global::Gtk.Button button21;

	private global::Gtk.Button button22;

	private global::Gtk.Button button23;

	private global::Gtk.Button button24;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = -11;
		// Container child vbox2.Gtk.Box+BoxChild
		this.resbox = new global::Gtk.Entry();
		this.resbox.HeightRequest = 80;
		this.resbox.Sensitive = false;
		this.resbox.CanFocus = true;
		this.resbox.Name = "resbox";
		this.resbox.IsEditable = false;
		this.resbox.HasFrame = false;
		this.resbox.InvisibleChar = '•';
		this.vbox2.Add(this.resbox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.resbox]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.numbox = new global::Gtk.Entry();
		this.numbox.HeightRequest = 73;
		this.numbox.CanFocus = true;
		this.numbox.Name = "numbox";
		this.numbox.IsEditable = true;
		this.numbox.ActivatesDefault = true;
		this.numbox.InvisibleChar = '•';
		this.vbox2.Add(this.numbox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.numbox]));
		w2.Position = 1;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(5)), false);
		this.table1.HeightRequest = 229;
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(1));
		this.table1.ColumnSpacing = ((uint)(1));
		// Container child table1.Gtk.Table+TableChild
		this.button10 = new global::Gtk.Button();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table1.Add(this.button10);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.button10]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(3));
		w3.RightAttach = ((uint)(4));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table1.Add(this.button11);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.button11]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table1.Add(this.button12);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button12]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table1.Add(this.button13);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button13]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button14 = new global::Gtk.Button();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table1.Add(this.button14);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.button14]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table1.Add(this.button15);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.button15]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button16 = new global::Gtk.Button();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table1.Add(this.button16);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.button16]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table1.Add(this.button17);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.button17]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button18 = new global::Gtk.Button();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString("raiz");
		this.table1.Add(this.button18);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.button18]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(4));
		w11.RightAttach = ((uint)(5));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button19 = new global::Gtk.Button();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table1.Add(this.button19);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.button19]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.LeftAttach = ((uint)(4));
		w12.RightAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button20 = new global::Gtk.Button();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table1.Add(this.button20);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.button20]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		w13.LeftAttach = ((uint)(3));
		w13.RightAttach = ((uint)(4));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button21 = new global::Gtk.Button();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString("%");
		this.table1.Add(this.button21);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.button21]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button22 = new global::Gtk.Button();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString(",");
		this.table1.Add(this.button22);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.button22]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button23 = new global::Gtk.Button();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table1.Add(this.button23);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.button23]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button24 = new global::Gtk.Button();
		this.button24.CanDefault = true;
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table1.Add(this.button24);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.button24]));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table1.Add(this.button6);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.button6]));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table1.Add(this.button7);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.button7]));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("C");
		this.table1.Add(this.button8);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.button8]));
		w21.LeftAttach = ((uint)(4));
		w21.RightAttach = ((uint)(5));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("x²");
		this.table1.Add(this.button9);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.LeftAttach = ((uint)(4));
		w22.RightAttach = ((uint)(5));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add(this.table1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 289;
		this.DefaultHeight = 385;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button24.Clicked += new global::System.EventHandler(this.SevenClicked);
	}
}
